name: curtn-app
services:
- name: curtn-api
  source_dir: /
  run_command: yarn start
  environment_slug: node-js
  instance_count: 1
  instance_size_slug: basic-xxs
  http_port: 4000
  routes:
  - path: /graphql
  - path: /api
static_sites:
- name: curtn-web
  source_dir: packages/web
  build_command: yarn build
  output_dir: dist
  routes:
  - path: /
